"""add_model_metrics_and_events_tables

Revision ID: 2e5e4ab1cc1a
Revises: 7b5626346da3
Create Date: 2026-06-03 22:49:58.654795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5e4ab1cc1a'
down_revision: Union[str, Sequence[str], None] = '7b5626346da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cortex_model_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('routed_by', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cortex_model_events_id'), 'cortex_model_events', ['id'], unique=False)
    op.create_index(op.f('ix_cortex_model_events_model_name'), 'cortex_model_events', ['model_name'], unique=False)
    op.create_index(op.f('ix_cortex_model_events_provider_name'), 'cortex_model_events', ['provider_name'], unique=False)
    op.create_index(op.f('ix_cortex_model_events_task_type'), 'cortex_model_events', ['task_type'], unique=False)
    op.create_table('cortex_model_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cortex_model_metrics_id'), 'cortex_model_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_cortex_model_metrics_model_name'), 'cortex_model_metrics', ['model_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cortex_model_metrics_model_name'), table_name='cortex_model_metrics')
    op.drop_index(op.f('ix_cortex_model_metrics_id'), table_name='cortex_model_metrics')
    op.drop_table('cortex_model_metrics')
    op.drop_index(op.f('ix_cortex_model_events_task_type'), table_name='cortex_model_events')
    op.drop_index(op.f('ix_cortex_model_events_provider_name'), table_name='cortex_model_events')
    op.drop_index(op.f('ix_cortex_model_events_model_name'), table_name='cortex_model_events')
    op.drop_index(op.f('ix_cortex_model_events_id'), table_name='cortex_model_events')
    op.drop_table('cortex_model_events')
    # ### end Alembic commands ###
