"""create_context_items_table

Revision ID: 40608697120f
Revises: 2e5e4ab1cc1a
Create Date: 2026-06-04 10:28:26.262128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40608697120f'
down_revision: Union[str, Sequence[str], None] = '2e5e4ab1cc1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_items_id'), 'context_items', ['id'], unique=False)
    op.create_index(op.f('ix_context_items_kind'), 'context_items', ['kind'], unique=False)
    op.create_index(op.f('ix_context_items_session_id'), 'context_items', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_items_session_id'), table_name='context_items')
    op.drop_index(op.f('ix_context_items_kind'), table_name='context_items')
    op.drop_index(op.f('ix_context_items_id'), table_name='context_items')
    op.drop_table('context_items')
    # ### end Alembic commands ###
