"""add hierarchical nodes

Revision ID: 48a574a20409
Revises: 40608697120f
Create Date: 2026-06-04 11:22:48.132725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a574a20409'
down_revision: Union[str, Sequence[str], None] = '40608697120f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hierarchical_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('vector_index', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['hierarchical_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hierarchical_nodes_id'), 'hierarchical_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_hierarchical_nodes_node_type'), 'hierarchical_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_hierarchical_nodes_parent_id'), 'hierarchical_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_hierarchical_nodes_path'), 'hierarchical_nodes', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hierarchical_nodes_path'), table_name='hierarchical_nodes')
    op.drop_index(op.f('ix_hierarchical_nodes_parent_id'), table_name='hierarchical_nodes')
    op.drop_index(op.f('ix_hierarchical_nodes_node_type'), table_name='hierarchical_nodes')
    op.drop_index(op.f('ix_hierarchical_nodes_id'), table_name='hierarchical_nodes')
    op.drop_table('hierarchical_nodes')
    # ### end Alembic commands ###
