"""add_columns_to_user_settings

Revision ID: c9ae46f41379
Revises: 9b7f6f0f8e21
Create Date: 2026-06-04 16:05:26.801638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ae46f41379'
down_revision: Union[str, Sequence[str], None] = '9b7f6f0f8e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('llm_model', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('embedding_model', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('vector_db', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('inference_engine', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('code_parsing', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('selected_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'selected_model')
    op.drop_column('user_settings', 'code_parsing')
    op.drop_column('user_settings', 'inference_engine')
    op.drop_column('user_settings', 'vector_db')
    op.drop_column('user_settings', 'embedding_model')
    op.drop_column('user_settings', 'llm_model')
    # ### end Alembic commands ###
