"""create_model_management_tables

Revision ID: de66352532a7
Revises: d4e8f1a2c3b0
Create Date: 2026-06-03 21:53:55.733485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de66352532a7'
down_revision: Union[str, Sequence[str], None] = 'd4e8f1a2c3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cortex_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.String(length=64), nullable=True),
    sa.Column('quantization', sa.String(length=64), nullable=True),
    sa.Column('vram_estimate', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cortex_models_id'), 'cortex_models', ['id'], unique=False)
    op.create_index(op.f('ix_cortex_models_name'), 'cortex_models', ['name'], unique=False)
    op.create_index(op.f('ix_cortex_models_provider_name'), 'cortex_models', ['provider_name'], unique=False)
    op.create_table('cortex_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('api_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cortex_providers_id'), 'cortex_providers', ['id'], unique=False)
    op.create_index(op.f('ix_cortex_providers_name'), 'cortex_providers', ['name'], unique=True)
    op.create_index(op.f('ix_cortex_automation_settings_id'), 'cortex_automation_settings', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_id'), 'knowledge_entries', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_source_path'), 'knowledge_entries', ['source_path'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_user_id'), 'knowledge_entries', ['user_id'], unique=False)
    op.drop_index(op.f('ix_memories_created_at'), table_name='memories')
    op.create_index(op.f('ix_pending_system_actions_id'), 'pending_system_actions', ['id'], unique=False)
    op.create_index(op.f('ix_pending_system_actions_user_id'), 'pending_system_actions', ['user_id'], unique=False)
    op.create_index(op.f('ix_proactive_notifications_id'), 'proactive_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_proactive_notifications_user_id'), 'proactive_notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_repository_profiles_id'), 'repository_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_repository_profiles_user_id'), 'repository_profiles', ['user_id'], unique=False)
    op.drop_index(op.f('ix_sync_runs_started_at'), table_name='sync_runs')
    op.create_index(op.f('ix_sync_runs_id'), 'sync_runs', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_sync_runs_id'), table_name='sync_runs')
    op.create_index(op.f('ix_sync_runs_started_at'), 'sync_runs', ['started_at'], unique=False)
    op.drop_index(op.f('ix_repository_profiles_user_id'), table_name='repository_profiles')
    op.drop_index(op.f('ix_repository_profiles_id'), table_name='repository_profiles')
    op.drop_index(op.f('ix_proactive_notifications_user_id'), table_name='proactive_notifications')
    op.drop_index(op.f('ix_proactive_notifications_id'), table_name='proactive_notifications')
    op.drop_index(op.f('ix_pending_system_actions_user_id'), table_name='pending_system_actions')
    op.drop_index(op.f('ix_pending_system_actions_id'), table_name='pending_system_actions')
    op.create_index(op.f('ix_memories_created_at'), 'memories', ['created_at'], unique=False)
    op.drop_index(op.f('ix_knowledge_entries_user_id'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_source_path'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_id'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_cortex_automation_settings_id'), table_name='cortex_automation_settings')
    op.drop_index(op.f('ix_cortex_providers_name'), table_name='cortex_providers')
    op.drop_index(op.f('ix_cortex_providers_id'), table_name='cortex_providers')
    op.drop_table('cortex_providers')
    op.drop_index(op.f('ix_cortex_models_provider_name'), table_name='cortex_models')
    op.drop_index(op.f('ix_cortex_models_name'), table_name='cortex_models')
    op.drop_index(op.f('ix_cortex_models_id'), table_name='cortex_models')
    op.drop_table('cortex_models')
    # ### end Alembic commands ###
